name = "QDiffView"
description = "Diff view widget"
author = "Yoshiki Shibukawa"
organization = ""
license = "The MIT License (MIT)"
qtmodules = ["Core", "Gui", "Widgets"]
version = [0, 1, 0]
project_start_year = 2016
qtpm_version = [0, 8, 1]
